#include "unit.h"

#include <stdio.h>

// uiNewImageFromFile decodes with the platform's built-in codecs, so the
// test embeds a valid PNG rather than shipping a data file; the image is
// written to a temporary file in the working directory (which is writable
// under both ctest and meson) and deleted afterwards.
//
// The embedded image is a 3x2 RGBA PNG (solid red, with sRGB/gAMA/pHYs
// metadata chunks) generated by System.Drawing; the chunks are ignored by
// every decoder, only the width and height matter here.

#define TESTPNG_FILENAME "uiimage-unit-test.png"
#define TESTPNG_MISSING_FILENAME "uiimage-unit-test-missing.png"

static const unsigned char testPNG[] = {
	0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D,
	0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x02,
	0x08, 0x06, 0x00, 0x00, 0x00, 0x9D, 0x74, 0x66, 0x1A, 0x00, 0x00, 0x00,
	0x01, 0x73, 0x52, 0x47, 0x42, 0x00, 0xAE, 0xCE, 0x1C, 0xE9, 0x00, 0x00,
	0x00, 0x04, 0x67, 0x41, 0x4D, 0x41, 0x00, 0x00, 0xB1, 0x8F, 0x0B, 0xFC,
	0x61, 0x05, 0x00, 0x00, 0x00, 0x09, 0x70, 0x48, 0x59, 0x73, 0x00, 0x00,
	0x0E, 0xC3, 0x00, 0x00, 0x0E, 0xC3, 0x01, 0xC7, 0x6F, 0xA8, 0x64, 0x00,
	0x00, 0x00, 0x11, 0x49, 0x44, 0x41, 0x54, 0x18, 0x57, 0x63, 0xF8, 0xCF,
	0xC0, 0xF0, 0x1F, 0x86, 0x19, 0x90, 0x39, 0x00, 0x9B, 0x7E, 0x0B, 0xF5,
	0x29, 0x0D, 0xDE, 0x81, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44,
	0xAE, 0x42, 0x60, 0x82,
};

static void writeTestPNG(void)
{
	FILE *f = fopen(TESTPNG_FILENAME, "wb");

	if (f != NULL) {
		fwrite(testPNG, 1, sizeof (testPNG), f);
		fclose(f);
	}
}

static void removeTestPNG(void)
{
	remove(TESTPNG_FILENAME);
}

static void imageLoadFromFile(void **state)
{
	uiInitOptions o = {0};
	uiImage *i;
	int width, height;

	assert_null(uiInit(&o));

	writeTestPNG();
	i = uiNewImageFromFile(TESTPNG_FILENAME);
	assert_non_null(i);
	uiImageGetSize(i, &width, &height);
	assert_int_equal(width, 3);
	assert_int_equal(height, 2);
	uiFreeImage(i);
	removeTestPNG();

	uiUninit();
}

static void imageLoadFromMissingFile(void **state)
{
	uiInitOptions o = {0};
	uiImage *i;

	assert_null(uiInit(&o));

	i = uiNewImageFromFile(TESTPNG_MISSING_FILENAME);
	assert_null(i);

	uiUninit();
}

#define imageUnitTest(f) cmocka_unit_test((f))

int imageRunUnitTests(void)
{
	const struct CMUnitTest tests[] = {
		imageUnitTest(imageLoadFromFile),
		imageUnitTest(imageLoadFromMissingFile),
	};

	return cmocka_run_group_tests_name("uiImage", tests, unitTestsSetup, unitTestsTeardown);
}
